// Code generated by "stringer -type LogLevel -linecomment"; DO NOT EDIT.

package plog

import "strconv"

const _LogLevel_name = "INFODEBUGERROR"

var _LogLevel_index = [...]uint8{0, 4, 9, 14}

func (i LogLevel) String() string {
	if i < 0 || i >= LogLevel(len(_LogLevel_index)-1) {
		return "LogLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
